// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hohigpghheotysoxiuiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvaGlncGdoaGVvdHlzb3hpdWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjM1NzMsImV4cCI6MjA3MDYzOTU3M30.wRaHM3z4t3rV0gHxSAOgmQCcS44neQH9ZV12LjLvITo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});